module.exports = {
  SYS_USERGROUP_OPTIONS: 'SYS_USERGROUP_OPTIONS',
  SYS_USER_OPTIONS: 'SYS_USER_OPTIONS',
  SYS_FUNCTIONGROUPS_OPTIONS: 'SYS_FUNCTIONGROUPS_OPTIONS',
  SYS_FUNCTION_OPTIONS: 'SYS_FUNCTION_OPTIONS',
  CUS_CUSTOMERS_OPTIONS: 'CUS_CUSTOMERS_OPTIONS',
};
